name: flutter_updater
description: flutter apk downloader for android with automatic install.
version: 0.1.6
homepage: "https://github.com/vickyleu/flutter_update"
github: "https://github.com/vickyleu/flutter_update"
publish_to: "https://pub.dev/packages/flutter_updater"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.6
  path: ^1.6.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.bond520.plugins.flutter_updater
    pluginClass: FlutterUpdatePlugin
